### PR TITLE
Added support for configurations, and added quickfix integration

### PR DESCRIPTION
**Pull request by ConnorWay32**
Added integration with Neovim's quickfix menu, as requested in #1 . In order to add this as a configuration option, the directory structure was modified, and a config.lua file was added. I also tweaked how the public API was structured.

I did change the fields of the locations table in line with what Neovim wants for setqflist, but the new variable names should be sensible enough to not cause any issues
```
cat -> text
path -> filename
line -> lnum
col -> col (unchanged)
```

I can try to make a workaround if this is an undesirable change though.

### CODE REVIEW

**Comment by ConnorWay32** [comment]
Should also mention that the quickfix behaviour is set with:
```lua
require("bacon").setup({
    quickfix = true
})
```

**Comment by Canop** [comment]
Thanks for the PR. It might take me a while to merge it, due to holidays and my lack of experience of neovim quickfix.

**Comment by ConnorWay32** [comment]
No worries, general usage of quickfix is `:copen` to open the window, or `:cwindow / :cw` to only open it if there are errors. `:cnext / :cn` and `:cprev / :cp` are used to navigate between the different error messages, though you'd probably want those bound to keymaps. I personally use [folke/trouble.nvim](https://github.com/folke/trouble.nvim) as a replacer for the menu itself, but it can still use the native Neovim quickfix list.

**Comment by ConnorWay32** [comment]
Tweaked the config for quickfix to be 
```lua
require("bacon").setup({
    quickfix = {
        enabled = true
    }
})
```
To make it easier to add quickfix related configuration settings in the future (e.g. triggering events, adding notifications)

**Pull request merged**
