### PR TITLE
added event trigger for quickfix (default on)

### PR DESCRIPTION
**Pull request by ConnorWay32**
Added the QuickFixCmdPost event trigger when the quickfix list gets populated. This event normally fires after running native quickfix commands like  `:grep` or `:make`, so this change just makes it play nicely for any autocommands using that event. I added a configuration option that defaulted as enabled, because while this is fairly intuitive functionality, some users may not wish to have the event triggered.

(The change to the quotation marks was just my autoformatter, can change it if you have strong feelings on it)

### CODE REVIEW

**Comment by Canop** [comment]
`event` doesn't seem very obvious. Maybe something like `auto_open` ?

**Comment by ConnorWay32** [comment]
Well, it's referred to as an event within the Neovim API, so I felt that it was the most appropriate term for it. It also doesn't open anything automatically, so `auto open` sounds a little misleading to me. Perhaps `event_trigger`?

**Comment by Canop** [comment]
Ok, can you improve the clarity with a comment ?

**Comment by Canop** [comment]
Looks good to me. I'll merge if you don't want to make other changes

**Comment by ConnorWay32** [comment]
I've added a comment to the event trigger in the code, is that what you meant? The addition to the readme already had a description comment.

**Pull request merged**
